### ISSUE TITLE
How do we build this?

### ISSUE THREAD

**Issue by davidfarah2003** [cckuailong/HackChrome#1]
I have never touched a go code, and everything I tried didn't work. Can anyone help?

**Comment by cckuailong** [comment]
There are builded binary file in the releases for the Win (386 and x64).
If you'd like to build it yourself, you can install the Golang and run the command "go build main.go"

**Comment by davidfarah2003** [comment]
The binary file was detected by antiviruses so i wanted to change the source code a bit.
However, after a lot of searching and trying I figured out how to do it for windows by installing gcc with msys2. But somehow my file ended up being 12 mb. How did you reduce it to 5?

**Comment by cckuailong** [comment]
1. `go build -ldflags="-w -s" main.go` The DWARF debugging information and symbol information will be removed
2. Use upx to compress the binary file.

With the steps above, you can reduce the size of it.

**Comment by davidfarah2003** [comment]
Thank you! there are still some issues with getting v80 passwords but it's good enough for my purpose.
